Add static asset build & upload to `build` script

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -4,5 +4,15 @@
 #
 
 builddir="$(git rev-parse --show-toplevel)"
+static_assets_bucket="aws-cms-oit-iusg-spe-easi-dev-easi-dev-static-assets"
 
-( set -x -u ; go build -a -o "$builddir"/bin/easi "$builddir"/cmd/easi )
+( set -x -u ; go build -a -o "$builddir"/bin/easi "$builddir"/cmd/easi ) || exit
+
+if bash +x -u -c "$(aws s3 ls "$static_assets_bucket" 1>/dev/null)" ; then
+  ( set -x -u ;
+    yarn run build || exit
+    aws s3 sync --no-progress build/ "$static_assets_bucket"
+  )
+else
+  echo "Could not read the S3 bucket. Are you authenticated?" 1>&2
+fi
