Add check for zero-length ssm result
This is because aws-cli returns zero even when it fails, for reasons

diff --git a/scripts/set_flyway_env b/scripts/set_flyway_env
--- a/scripts/set_flyway_env
+++ b/scripts/set_flyway_env
@@ -2,6 +2,11 @@
 
 ssm_params="$(set -x ; aws ssm get-parameters-by-path --path /"${APP_ENV}"/easi-app/db/)" || exit
 
+if [[ -z "$ssm_params" ]] ; then
+  echo "Failed to retrieve parameters from SSM." 1>&2
+  exit 1
+fi
+
 _ssm() {
   param="$1"
   jq --raw-output ".Parameters[] | select(.Name | contains(\"$param\")) | .Value" <<< "$ssm_params" || exit
