update code coverage call

diff --git a/scripts/testsuite b/scripts/testsuite
--- a/scripts/testsuite
+++ b/scripts/testsuite
@@ -7,3 +7,23 @@ builddir="$(git rev-parse --show-toplevel)"
 export EMAIL_TEMPLATE_DIR=$builddir/pkg/email/templates
 
 ( set -x -u ; exec "$builddir"/bin/easi test )
+
+# Convert go-coverage.out to txt and html
+go tool cover -func=go-coverage.out -o "go-coverage.txt"
+go tool cover -html=go-coverage.out -o "go-coverage.html"
+# parse out the total coverage percentage which is on the line with (statements) and strip off the % sign
+# https://unix.stackexchange.com/questions/305190/remove-last-character-from-string-captured-with-awk
+percent=$(grep '(statements)' "go-coverage.txt" | awk '{print substr($NF, 1, length($NF)-1)}')
+# Commenting out threshold percantage and build fail unitl decision
+#goal_percent=50
+# using a oneline python function to test if percent is less than goal and return a proper exit code
+#if python -c "exit(1) if ${percent} < ${goal_percent} else exit()"; then
+    # coverage is good
+    echo "total coverage is ${percent}%"
+#else
+    # coverage is under goal
+    #echo -e "${RED}total coverage has dropped to ${percent}% needs to be at least ${goal_percent}%${NC}"
+    # fail build
+    # commenting out the build failure line since we don't want to fail the build yet until we've had further discussions
+    #exit 1
+#fi
